lab_04/InternetShop/cart/urls.py
from django.urls import path
from . import views
app_name = "cart"
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

lab_04/InternetShop/myshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from users import views as user_views


app_name='shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('users.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include(('shop.urls','shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_04/InternetShop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

lab_04/InternetShop/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        # index_together = (('id', 'slug'),)
        indexes = [
            models.Index(fields=['id','slug']),
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])
    def __str__(self):
        return self.name

lab_04/InternetShop/shop/views.py
from django.shortcuts import render
from cart.forms import CartAddProductForm
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
import requests

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    r = requests.get('https://catfact.ninja/fact?max_length=100')

    return render(request, 'shop/product/list.html', {'category': category,
                                                    'categories': categories,
                                                    'products': products,
                                                    'fun_fact': r.json()['fact']})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,'cart_product_form': cart_product_form})

lab_04/InternetShop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}

    <link href="{% static '/css/detail.css' %}" rel="stylesheet">
    <div class="product-detail">
        <div class="image-container">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'images/img.png' %}{% endif %}">
            <h1>{{ product.name }}</h1>
        </div>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">{{ product.price }} BYN</p>
        {{ product.description|linebreaks }}
    </div>
<p class="price">{{ product.price }} BYN</p>
<form action="{% url 'cart:cart_add' product.id %}" method="post">
    Количество {{ cart_product_form.quantity }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзину">
</form>
{% endblock %}

lab_04/InternetShop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% if category %}{{ category.name }}{% else %}Еда{% endif %}
{% block content %}
<link href="{% static '/css/list.css' %}" rel="stylesheet">
<div class="wrapper">


    <div class="sidebar">
        
        <ul class="sidebar_categories">
            <li {% if not category %}class="selected category"{% else %}class="category"{% endif %}>
                <a class="category_link" href="{% url 'shop:product_list' %}">Все</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected category"{% else %}class="category"{% endif %}>
                    <a class="category_link" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <h1>{% if category %}{{ category.name }}{% else %}Все{% endif %}</h1>
    <div id="main" class="product-list{% if products|length == 1 %} single-item{% endif %}">
        {% for product in products %}
            <div class="item">
                
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'images/img.png' %}{% endif %}">

                    <div class="item-info">
                        <div class="item-info_name">{{product.name }}</div>
                        <div class="item-info_description">{{product.description}}</div>
                        <div class="item-info_order">
                            <div class="item-info_price">{{ product.price }} руб.</div>
                            <a class="item-info_order_button" style="color:white;" href="{{ product.get_absolute_url }}">Заказать</a>
                        </div>
                        
                    </div>
                
            </div>
        {% endfor %}
    </div>
</div>
<h3>
    Интересный факт про котов: {{fun_fact}}
</h3>
{% endblock %}