lab_04/InternetShop/cart/urls.py
from django.urls import path
from . import views
app_name = "cart"
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

lab_04/InternetShop/myshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from users import views as user_views


app_name='shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('users.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include(('shop.urls','shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_04/InternetShop/orders/urls.py
from django.urls import path
from . import views
app_name = "orders"
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

lab_04/InternetShop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

lab_04/InternetShop/cart/models.py
from django.db import models

# Create your models here.

lab_04/InternetShop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

lab_04/InternetShop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
import requests


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    dog_pic = requests.get("https://dog.ceo/api/breeds/image/random")
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'dog': dog_pic.json()['message']})

lab_04/InternetShop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}
    <link href="{% static '/css/cart.css' %}" rel="stylesheet">
    <h1>Корзина</h1>
    <div class="cart">
        <div>
        {% for item in cart %}
            {% with product=item.product %}
                <div class="cart_item">
                    <a class="cart_item_image" href="{{ product.get_absolute_url }}">
                         <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'images/img.png' %}
                                {% endif %}">
                    </a>
                    <div class="cart_item_description">
                        <div class="cart_item_name">{{ product.name }}</div>
                        <div class="cart_item_product_description">{{product.description}}</div>
                        <div class="cart_item_price">{{ item.price }} руб. x {{ item.quantity }} = {{ item.total_price }} руб.</div>
                        
                        <a class="cart-button" href="{% url 'cart:cart_remove' product.id%}">Удалить</a>
                    </div>
                </div>
            {% endwith %}
        {% endfor %}
        <div class="total">
            <div class="total_title">Итого:</div>
            
            <div class="total_value">{{ cart.get_total_price }} руб.</div>
        </div>
        </div>
    </div>
    <div class="cart_buttons">
    <a href="{% url 'orders:order_create' %}"  class="cart-button">Оформить заказ</a>
       <a href="{% url 'shop:product_list' %}"class="cart-button grey">Вернуться в меню</a>
    </p>
    <h3>Веселая картинка собачки для вас)</h3>
    <div>
        <img src="{{ dog }}" alt="dog pic">
    </div>
{% endblock %}